### ISSUE TITLE
DOI for citation

### ISSUE THREAD

**Issue by lacan** [MarkZaidi/Universal-StarDist-for-QuPath#3]
Dear all, 

Could you create the final DOI for this tool? Right now using the "Cite" button yields this
Zaidi, M., McKee, T., & Wouters, B. (2021). Universal-StarDist-for-QuPath (Version 1.0.0) [Computer software]. **https://doi.org/TBD**

**Comment by MarkZaidi** [comment]
Updated [citation.cff](https://github.com/MarkZaidi/Universal-StarDist-for-QuPath/blob/main/citation.cff) to include a DOI generated from a Research Gate snapshot of the current repository. The full citation is as follows:

`Zaidi, M., McKee, T., & Wouters, B. (2021). Universal-StarDist-for-QuPath (Version 1.0.0) [Computer software]. https://doi.org/10.13140/RG.2.2.36267.11046`
