### ISSUE TITLE
ReadMe Link Update

### ISSUE THREAD

**Issue by finglis** [MarkZaidi/Universal-StarDist-for-QuPath#4]
Hi Mark, 

Just spotted in the readme there is a minor link update required to the Qupath docs from https://qupath.readthedocs.io/en/stable/docs/advanced/stardist.html to https://qupath.readthedocs.io/en/stable/docs/deep/stardist.html 

Thanks,
Fiona

**Comment by MarkZaidi** [comment]
Thanks for the heads up, fixed!
